insert into Duties (title, description, priority, date, time, status) values ('Budget/Accounting Analyst II', 'Ictalurus furcatus', 2, '5/20/2025', '12:03 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Senior Cost Accountant', 'Pitangus sulphuratus', 2, '6/18/2025', '2:59 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Project Manager', 'Semnopithecus entellus', 0, '5/2/2025', '3:52 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Chemical Engineer', 'Tetracerus quadricornis', 0, '4/16/2025', '12:54 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Payment Adjustment Coordinator', 'Parus atricapillus', 2, '4/30/2025', '10:30 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Senior Developer', 'Tadorna tadorna', 0, '4/30/2025', '6:43 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Sales Representative', 'Odocoileus hemionus', 2, '6/24/2025', '10:09 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Systems Administrator III', 'Bugeranus caruncalatus', 2, '4/18/2025', '2:44 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Environmental Tech', 'Bassariscus astutus', 0, '4/30/2025', '7:44 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Technical Writer', 'Microcebus murinus', 0, '4/29/2025', '4:44 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Legal Assistant', 'Stercorarius longicausus', 2, '4/17/2025', '6:40 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Marketing Assistant', 'Colaptes campestroides', 0, '6/15/2025', '4:28 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Administrative Assistant IV', 'Eubalaena australis', 0, '5/8/2025', '11:13 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Environmental Specialist', 'Uraeginthus bengalus', 0, '6/28/2025', '12:26 PM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Account Coordinator', 'Ateles paniscus', 2, '5/19/2025', '6:27 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Systems Administrator III', 'Cercopithecus aethiops', 0, '6/8/2025', '4:22 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Assistant Professor', 'Macropus fuliginosus', 0, '4/30/2025', '12:23 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Human Resources Manager', 'Lorythaixoides concolor', 2, '4/22/2025', '9:29 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Food Chemist', 'Gyps bengalensis', 1, '5/5/2025', '8:30 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Sales Associate', 'Camelus dromedarius', 0, '5/18/2025', '4:13 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Teacher', 'Oxybelis fulgidus', 0, '5/10/2025', '5:22 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Occupational Therapist', 'Choriotis kori', 0, '4/18/2025', '4:46 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Financial Analyst', 'Actophilornis africanus', 1, '5/2/2025', '10:51 PM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Senior Financial Analyst', 'Branta canadensis', 2, '5/27/2025', '3:27 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Nurse', 'Tamiasciurus hudsonicus', 2, '6/18/2025', '6:15 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Structural Engineer', 'Felis caracal', 0, '4/28/2025', '11:24 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Product Engineer', 'Gyps bengalensis', 2, '5/24/2025', '12:04 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Software Engineer II', 'Oryx gazella', 0, '5/9/2025', '2:29 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Civil Engineer', 'Tringa glareola', 0, '5/10/2025', '12:58 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('VP Quality Control', 'Varanus albigularis', 0, '6/21/2025', '5:19 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Payment Adjustment Coordinator', 'Sceloporus magister', 0, '4/25/2025', '1:54 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Nuclear Power Engineer', 'Equus burchelli', 2, '6/20/2025', '6:10 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Internal Auditor', 'Neophron percnopterus', 0, '5/22/2025', '2:51 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Senior Developer', 'unavailable', 0, '4/18/2025', '12:03 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Assistant Media Planner', 'Ctenophorus ornatus', 0, '5/28/2025', '1:18 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Automation Specialist IV', 'Cervus elaphus', 2, '5/29/2025', '11:06 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Nurse Practicioner', 'Macaca radiata', 2, '4/20/2025', '2:33 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Assistant Manager', 'Lycaon pictus', 2, '4/20/2025', '10:46 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Dental Hygienist', 'Microcebus murinus', 0, '4/20/2025', '9:43 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Administrative Officer', 'Ursus americanus', 2, '6/17/2025', '3:26 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Staff Scientist', 'Anas bahamensis', 0, '5/16/2025', '3:52 PM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Software Test Engineer II', 'Chlamydosaurus kingii', 0, '5/8/2025', '12:14 PM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Database Administrator III', 'Dusicyon thous', 0, '4/17/2025', '11:21 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('VP Quality Control', 'Seiurus aurocapillus', 2, '4/20/2025', '12:05 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('VP Accounting', 'unavailable', 2, '6/10/2025', '10:20 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Librarian', 'Mycteria leucocephala', 0, '4/21/2025', '6:23 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Recruiting Manager', 'Kobus leche robertsi', 2, '6/17/2025', '2:38 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Geologist III', 'Bassariscus astutus', 2, '6/23/2025', '4:19 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Structural Engineer', 'Mephitis mephitis', 0, '5/26/2025', '4:29 PM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Engineer IV', 'Limosa haemastica', 0, '5/24/2025', '4:03 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Quality Engineer', 'Tamiasciurus hudsonicus', 0, '4/27/2025', '10:07 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Web Developer I', 'unavailable', 0, '6/7/2025', '11:58 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Media Manager I', 'Echimys chrysurus', 0, '5/10/2025', '12:56 PM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Payment Adjustment Coordinator', 'Cordylus giganteus', 0, '6/25/2025', '1:08 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Help Desk Technician', 'Snycerus caffer', 0, '5/11/2025', '2:26 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Chief Design Engineer', 'Acrobates pygmaeus', 0, '5/13/2025', '4:24 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Professor', 'Mycteria leucocephala', 0, '4/28/2025', '2:00 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Senior Sales Associate', 'Meleagris gallopavo', 0, '5/24/2025', '10:15 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Staff Scientist', 'Nucifraga columbiana', 2, '5/16/2025', '7:28 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Physical Therapy Assistant', 'Microcavia australis', 0, '5/11/2025', '6:18 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Occupational Therapist', 'Alectura lathami', 0, '4/17/2025', '9:32 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Chemical Engineer', 'Stercorarius longicausus', 0, '6/14/2025', '5:33 PM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Geologist III', 'Xerus sp.', 1, '6/23/2025', '11:33 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Senior Financial Analyst', 'Spermophilus tridecemlineatus', 0, '5/24/2025', '8:50 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Quality Engineer', 'Psophia viridis', 0, '5/18/2025', '10:42 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Research Assistant IV', 'Xerus sp.', 2, '5/25/2025', '4:48 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Media Manager II', 'Cacatua galerita', 0, '4/30/2025', '8:19 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Technical Writer', 'Actophilornis africanus', 2, '4/19/2025', '7:40 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Occupational Therapist', 'Choriotis kori', 0, '5/11/2025', '6:25 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Account Representative III', 'Oxybelis fulgidus', 0, '5/30/2025', '6:54 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Quality Control Specialist', 'Cathartes aura', 0, '6/13/2025', '11:09 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Database Administrator III', 'Creagrus furcatus', 0, '5/11/2025', '12:54 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Assistant Manager', 'Phascogale tapoatafa', 0, '6/29/2025', '11:56 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('General Manager', 'Lorythaixoides concolor', 0, '6/27/2025', '8:21 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Design Engineer', 'Ara ararauna', 0, '5/31/2025', '6:21 PM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Pharmacist', 'Ovis ammon', 0, '4/16/2025', '7:26 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Registered Nurse', 'Francolinus coqui', 2, '4/19/2025', '7:40 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Accounting Assistant IV', 'Eremophila alpestris', 0, '4/21/2025', '9:13 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Senior Developer', 'Mustela nigripes', 0, '4/21/2025', '6:22 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Nuclear Power Engineer', 'Oryx gazella callotis', 1, '6/2/2025', '4:57 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Mechanical Systems Engineer', 'Petaurus norfolcensis', 2, '5/14/2025', '7:13 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Assistant Media Planner', 'Amphibolurus barbatus', 0, '4/30/2025', '3:13 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Administrative Officer', 'Theropithecus gelada', 0, '6/12/2025', '2:12 PM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Geological Engineer', 'Actophilornis africanus', 0, '5/17/2025', '7:40 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Paralegal', 'Corvus brachyrhynchos', 2, '6/29/2025', '1:17 PM', 1);
insert into Duties (title, description, priority, date, time, status) values ('VP Accounting', 'Picoides pubescens', 2, '5/7/2025', '1:57 PM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Tax Accountant', 'Estrilda erythronotos', 0, '6/19/2025', '7:30 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Nurse Practicioner', 'Genetta genetta', 0, '5/30/2025', '12:59 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Senior Financial Analyst', 'Ardea cinerea', 2, '4/18/2025', '10:14 AM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Marketing Assistant', 'Actophilornis africanus', 0, '5/26/2025', '1:32 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('VP Marketing', 'Tachybaptus ruficollis', 2, '4/21/2025', '7:23 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Internal Auditor', 'Trachyphonus vaillantii', 0, '5/3/2025', '8:52 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Developer II', 'unavailable', 1, '5/4/2025', '9:37 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Civil Engineer', 'Lepus townsendii', 2, '4/30/2025', '11:29 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Quality Engineer', 'Paradoxurus hermaphroditus', 0, '6/19/2025', '3:05 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Computer Systems Analyst I', 'Trachyphonus vaillantii', 0, '6/26/2025', '7:47 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Internal Auditor', 'Boselaphus tragocamelus', 0, '5/18/2025', '1:41 AM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Mechanical Systems Engineer', 'Amazona sp.', 0, '6/7/2025', '12:13 PM', 0);
insert into Duties (title, description, priority, date, time, status) values ('Analyst Programmer', 'Tursiops truncatus', 0, '5/29/2025', '5:31 PM', 1);
insert into Duties (title, description, priority, date, time, status) values ('Sales Representative', 'Hystrix cristata', 0, '6/12/2025', '6:32 AM', 0);
